stages:
  - test
  - deploy

test:
  image: thecodingmachine/php:8.1-v4-cli
  stage: test
  cache:
    paths:
      - vendor/
  before_script:
    - composer config --global gitlab-token.gitlab.com ${COMPOSER_CICD_READ}
    - composer install --no-scripts
  script:
    - composer test -- --log-junit report.xml --coverage-html=tests/coverage --coverage-text --colors=never
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - ./tests/coverage

deploy:
  image: curlimages/curl:latest
  stage: deploy
  needs:
    - test
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data $version "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'